# Generated by Django 2.0.4 on 2018-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Date')),
                ('type', models.IntegerField(choices=[(1, 'start'), (2, 'end')], verbose_name='Call type')),
                ('call_id', models.IntegerField(verbose_name='Code')),
                ('source', models.CharField(blank=True, max_length=11, null=True, verbose_name='Sender')),
                ('destination', models.CharField(blank=True, max_length=11, null=True, verbose_name='To')),
                ('bill', models.ManyToManyField(to='bills.Bill')),
            ],
            options={
                'verbose_name': 'Call',
                'ordering': ['-id'],
            },
        ),
    ]
