# Generated by Django 2.0.4 on 2018-05-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='bill',
        ),
    ]
