# Generated by Django 2.0.4 on 2018-04-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20180417_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=11, verbose_name='Destinatário')),
                ('call_start_date', models.DateField(verbose_name='Data da Ligação')),
                ('call_start_time', models.TimeField(verbose_name='Horário da Ligação')),
                ('call_price', models.FloatField(verbose_name='Valor da chamada')),
            ],
            options={
                'verbose_name': 'Conta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('type', models.IntegerField(choices=[(1, 'Start'), (2, 'End')], verbose_name='Tipo da ligação')),
                ('call_id', models.CharField(max_length=32, verbose_name='Código')),
                ('source', models.CharField(max_length=11, verbose_name='Remetente')),
                ('destination', models.CharField(max_length=11, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Chamada',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='cost',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], verbose_name='Situação'),
        ),
    ]
