# Generated by Django 2.0.4 on 2018-05-20 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_remove_call_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Sender'),
        ),
    ]
