# Generated by Django 2.0.4 on 2018-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_bill_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
