# Generated by Django 2.0.4 on 2018-05-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20180508_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
