# Generated by Django 2.0.4 on 2018-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20180508_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='call_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Código'),
        ),
    ]
