# Generated by Django 2.0.4 on 2018-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20180510_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='source',
            field=models.CharField(default=1, max_length=11, verbose_name='Remetente'),
            preserve_default=False,
        ),
    ]
