# Generated by Django 2.0.4 on 2018-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_bill_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='call_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da chamada'),
        ),
    ]
