# Generated by Django 2.0.4 on 2018-05-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_auto_20180513_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='call_type',
            new_name='type',
        ),
    ]
