# Generated by Django 2.0.4 on 2018-05-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_auto_20180517_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='call_id',
            field=models.IntegerField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Bill', to_field='call_id', verbose_name='Código'),
        ),
    ]
