version: '3'

services:
  web:
    container_name: django
    environment:
      TIME_ZONE: America/Sao_Paulo
    build: .
    volumes:
      - ./call_project:/source
    expose:
      - "8000"
    depends_on:
      - database
      - redis
    links:
        - database
        - redis
    command: bash -c "sleep 6 && printf 'yes' | python3 manage.py collectstatic && python3 manage.py migrate && python3 manage.py loaddata calls/fixtures/costs.json && python3 manage.py loaddata calls/fixtures/bills.json && python3 manage.py loaddata calls/fixtures/calls.json && gunicorn call_project.wsgi -b 0.0.0.0:8000"
  celery:
    container_name: celery
    environment:
      TIME_ZONE: America/Sao_Paulo
    build: .
    command: celery -A call_project worker --concurrency=4 -l info
    volumes:
      - ./call_project:/source
    depends_on:
      - database
      - redis
  nginx:
    container_name: nginx
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
    volumes:
      - ./call_project:/source
      - ./configs/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
      - database
      - redis
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: masterpass
      POSTGRES_USER: userdb
      POSTGRES_DB: call_project
  redis:
    container_name: redis
    image: redis:latest
    container_name: call_redis
    ports:
     - '6379:6379'