version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: masterpass
      POSTGRES_USER: userdb
      POSTGRES_DB: call_project
  celery:
    environment:
      TIME_ZONE: America/Sao_Paulo
    build: .
    command: celery -A call_project worker -l info
    volumes:
      - ./call_project:/source
    depends_on:
      - database
      - redis
  web:
    environment:
      TIME_ZONE: America/Sao_Paulo
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./call_project:/source
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
  redis:
    image: redis:latest
    container_name: call_redis
    ports:
     - '6379:6379'