version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./call_project:/source
      - ./configs/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
      - database
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: masterpass
      POSTGRES_USER: userdb
      POSTGRES_DB: call_project
  celery:
    environment:
      TIME_ZONE: America/Sao_Paulo
    build: .
    command: celery -A call_project worker -l info
    volumes:
      - ./call_project:/source
    depends_on:
      - database
      - redis
  web:
    environment:
      TIME_ZONE: America/Sao_Paulo
    build: .
    command: bash -c "python3 manage.py migrate && printf 'yes' | python3 manage.py collectstatic && gunicorn call_project.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./call_project:/source
    expose:
      - "8000"
    depends_on:
      - database
      - redis
  redis:
    image: redis:latest
    container_name: call_redis
    ports:
     - '6379:6379'