# Generated by Django 2.0.4 on 2018-04-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costs',
            new_name='Cost',
        ),
    ]
