# Generated by Django 2.0.4 on 2018-04-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20180418_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='type',
            new_name='call_type',
        ),
    ]
