# Generated by Django 2.0.4 on 2018-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_auto_20180426_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='call_id',
            field=models.CharField(max_length=32, null=True, verbose_name='Código'),
        ),
    ]
