# Generated by Django 2.0.4 on 2018-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_bill_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='duration',
            field=models.TimeField(null=True, verbose_name='Duração da Ligação'),
        ),
    ]
