# Generated by Django 2.0.4 on 2018-05-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_remove_call_bill'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='calls',
            field=models.ManyToManyField(to='calls.Call'),
        ),
    ]
