# Generated by Django 2.0.4 on 2018-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='bill',
            name='call_start_date',
            field=models.DateField(null=True, verbose_name='Start call date'),
        ),
        migrations.AddField(
            model_name='bill',
            name='call_start_time',
            field=models.TimeField(null=True, verbose_name='Start call time'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='call_id',
            field=models.IntegerField(unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='call_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost of call'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='destination',
            field=models.CharField(max_length=11, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration time'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='source',
            field=models.CharField(max_length=11, verbose_name='Sender'),
        ),
    ]
