# Generated by Django 2.0.4 on 2018-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20180519_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='duration',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Duration time'),
        ),
    ]
