# Generated by Django 2.0.4 on 2018-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-id'], 'verbose_name': 'Cost setting'},
        ),
        migrations.AlterField(
            model_name='cost',
            name='connection_cost',
            field=models.FloatField(verbose_name='Price of call'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_per_minute',
            field=models.FloatField(verbose_name='Price per minute'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='end_period',
            field=models.TimeField(verbose_name='End of trading period'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='initial_period',
            field=models.TimeField(verbose_name='Start of trading period'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], verbose_name='Status'),
        ),
    ]
